POST http://localhost:9196/keywords
Content-Type: text/plain

ВЕДУЩАЯ ОНЛАЙН ТРАНСЛЯЦИЙ

В связи со стремительным развитием нашей мобильной стримминговой платформы во всём мире нам требуются стримеры на удалённую работу.
На данный момент на платформе зарегистрировано более 100+ миллионов человек по всему миру, и аудитория постоянно растет. Общайтесь со зрителями во время прямого эфира, знакомьтесь, дружите с людьми по всему земному шару и одновременно зарабатывайте!

Обязанности
• вести прямые трансляции;
• создавать развлекательный контент;
• общение с аудиторией – работа на стримах;


Условия:
• Работа удаленно: возможность работать из любого уголка мира, где есть хороший интернет.
• Заработная плата, которая будет расти по мере появления у Вас постоянных зрителей и поклонников и зависеть от частоты Ваших выходов в эфир.
• Стабильные выплаты: 2 раза в месяц в долларах США.
• Всесторонняя поддержка: Вас будет курировать наш агент, он поможет Вам с обучением, окажет техническую поддержку и всегда ответит на все Ваши вопросы.
• Свободный график работы: чем больше и лучше Вы работаете, тем выше Ваш доход, график Вы регулируете сами.
• Интересные дополнительные бонусы, которые предоставляет платформа.
• Возможность заработать $500 за неделю.
• Никакого интима, 18+ контента – сразу бан.


Требования:
• Наличие смартфона с хорошей камерой для проведения прямых эфиров. Штатив, свет и антураж – только в плюс.
• Знание английского или других языков (испанский, арабский, азиатские языки) приветствуется, но не обязательно – у нас есть встроенный переводчик!
• Способность быстро располагать к себе людей и открыто выражать свои эмоции.
• Хорошее интернет-соединение.
• Желание очень много зарабатывать.
• Открытое общение с аудиторией.

Мы развиваем своих ведущих, помогаем им становиться известными и хорошо зарабатывать, при полной свободе действий и рабочего графика.

Откликнуться можно здесь:
https://remowork.ru/vacancy/vedushhaya-onlayn-translyaciy/

###
POST http://localhost:9196/keywords
Content-Type: text/plain

\#резюме #тильда

Привет, меня зовут Настя и я веб-дизайнер!

Я делаю лендинги на Тильде, а также простые многостраничники.

Срок изготовления: 3 дня (может увеличиваться в зависимости от количества правок и сложности работы)

Буду в постоянном контакте с вами, учту все ваши пожелания.

Оплата минимальная. Жду ваших заявок.

Пригласить в проект: @agangart


###
POST http://localhost:9196/keywords
Content-Type: text/plain

