GET http://localhost:3096/me
Accept: application/json

###
GET http://localhost:3096/chats/load
Accept: application/json

###
GET http://localhost:3096/chats/get
Accept: application/json

###
GET http://localhost:3096/messages/load/oneChat/-1001270798381
Accept: application/json

###

GET http://localhost:3096/messages/load/oneChat/-1001270798381?onlyNew=0
Accept: application/json

###

GET http://localhost:3096/messages/load/allChats
Accept: application/json

###

GET http://localhost:3096/messages/allChats?onlyNew=0
Accept: application/json

###
GET http://localhost:3096/messages/get/-1001270798381
Accept: application/json

###